[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.0"
axum = "0.7.5"
tokio = { version = "~1.38", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tower-http = { version = "0.5.2", features = ["cors"] }